# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c86513012ffdcced8b86c752338e43e1"
application_url = "https://at-bronze-wayne-gzip.trycloudflare.com"
embedded = true
name = "test-app"
handle = "test-app-11240"

[build]
automatically_update_urls_on_dev = true
dev_store_url = "miavai649.myshopify.com"
include_config_on_deploy = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "unauthenticated_read_checkouts,unauthenticated_read_product_listings,unauthenticated_write_checkouts,write_products"

[auth]
redirect_urls = [
  "https://at-bronze-wayne-gzip.trycloudflare.com/auth/callback",
  "https://at-bronze-wayne-gzip.trycloudflare.com/auth/shopify/callback",
  "https://at-bronze-wayne-gzip.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
